services:
  # PostgreSQL
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: event_admin
      POSTGRES_PASSWORD: event_pass
      POSTGRES_DB: event_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U event_admin -d event_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Веб-интерфейс для БД
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy

  # Сервис Java-приложения
  event_agency:
    build: .
    container_name: java_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/event_db
      SPRING_DATASOURCE_USERNAME: event_admin
      SPRING_DATASOURCE_PASSWORD: event_pass
      SPRING_PROFILES_ACTIVE: prod  # Явное указание профиля
    ports:
      - "8080:8080"
    restart: unless-stopped

  # Фронтенд-приложение
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=/api  # Переменная для Vite
    depends_on:
      - event_agency
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  postgres_data: