services:
  # PostgreSQL
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: event_admin
      POSTGRES_PASSWORD: event_pass
      POSTGRES_DB: event_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U event_admin -d event_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Веб-интерфейс для БД
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy

  # Сервис Java-приложения
  event_agency:
    build: .
    container_name: java_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/event_db
      SPRING_DATASOURCE_USERNAME: event_admin
      SPRING_DATASOURCE_PASSWORD: event_pass
      SPRING_PROFILES_ACTIVE: prod
      SPRING_FLYWAY_ENABLED: "true"  
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"  
      JAVA_OPTS: "-Xmx512m -Xms256m"
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://event_agency:8080/
    depends_on:
      - event_agency
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  postgres_data: