version: '3.8'

services:
  # PostgreSQL
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: event_admin
      POSTGRES_PASSWORD: event_pass
      POSTGRES_DB: event_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Веб-интерфейс для БД
  adminer:
    image: adminer
    restart: always
    ports:
    - "8081:8080"  
    depends_on:
      - db

    # Сервис Java-приложения
  demo:
    build: .  # Собираем из Dockerfile
    container_name: java_app
    depends_on:
      - db  # Ждём запуска PostgreSQL
    environment:
      # Подключение к БД (используем имя сервиса "postgres" вместо localhost)
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME: event_admin
      SPRING_DATASOURCE_PASSWORD: event_pass
    ports:
      - "8080:8080"  # Пробрасываем порт Java-приложения


volumes:
  postgres_data: